affine_trainable: false
auto_save: true
base_fun_name: silu
ckpt_path: ./model
device: cuda
grid: 8
grid_eps: 0.02
grid_range:
- -1
- 1
k: 3
mult_arity: 2
round: 0
sb_trainable: true
sp_trainable: true
state_id: 1
symbolic.funs_name.0:
- - x
  - '0'
  - '0'
  - '0'
  - '0'
- - x
  - '0'
  - x
  - '0'
  - '0'
- - x
  - '0'
  - 1/x^2
  - '0'
  - '0'
- - cos
  - '0'
  - x^2
  - '0'
  - '0'
- - '0'
  - '0'
  - x
  - '0'
  - x
symbolic.funs_name.1:
- - '0'
  - '0'
  - x
  - x
  - x
- - '0'
  - '0'
  - x
  - x
  - x^2
- - '0'
  - '0'
  - '0'
  - '0'
  - '0'
- - '0'
  - '0'
  - x
  - x
  - '0'
- - '0'
  - '0'
  - x
  - x
  - x^2
- - '0'
  - '0'
  - x
  - x
  - '0'
- - '0'
  - '0'
  - x
  - x
  - '0'
- - '0'
  - '0'
  - x
  - x
  - exp
- - '0'
  - '0'
  - x
  - x
  - '0'
- - '0'
  - '0'
  - x
  - x
  - '0'
symbolic.funs_name.2:
- - '0'
  - '0'
  - x
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
- - '0'
  - cos
  - exp
  - '0'
  - x
  - exp
  - x
  - '0'
  - x
  - '0'
- - '0'
  - x
  - cos
  - '0'
  - cos
  - sin
  - sin
  - '0'
  - exp
  - '0'
- - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
- - x
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
- - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
- - '0'
  - '0'
  - cos
  - '0'
  - x
  - x
  - '0'
  - '0'
  - x
  - '0'
- - '0'
  - '0'
  - cos
  - '0'
  - x
  - x
  - '0'
  - '0'
  - '0'
  - '0'
- - '0'
  - '0'
  - sin
  - '0'
  - '0'
  - x
  - '0'
  - '0'
  - '0'
  - '0'
symbolic_enabled: false
width:
- - 5
  - 0
- - 5
  - 0
- - 10
  - 0
- - 9
  - 0
